model:
  model_name: gpt-4o
  use_openai_api: True
  api_key: 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 
  temperature: 1.0
  max_tokens: 256
  n_choices: 3


experiement:
  out_dir: outputs/
  batch_inference: True
  n_batch: 2
  n_workers: 4
  prefetch: 2

prompt:
  template_dir: assets/prompt_templates
  use_example: True
  prompt_type: scoring
  input_types:
    geometry: ['rgb', 'normal']
    texture: ['rgb', 'albedo']
    material: ['rgb', 'metallic', 'roughness']
    plausibility: ['rgb']
    artifacts: ['rgb']
    preference: ['rgb']

data:
  src_path: assets/gobajverse_280k
  meta_path: assets/gobjaverse_280k.json
  example:
    num_example: 5 
    iter_per_example: 3
    meta_path: assets/example_scores.json

