model:
  model_name: gpt-4o
  use_openai_api: True
  api_key: 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 
  temperature: 1.0
  max_tokens: 256
  n_choices: 3

experiment:
  out_dir: outputs/
  batch_inference: True

data:
  src_path: datasets/gobjaverse_280k_test/
  meta_path: datasets/gobjaverse_280k_test.json
  example:
    num_level: 5 
    num_example_sampling: 3
    sample_interval: 0
    sample_offset: 0
    meta_path: assets/example_scores.json
  n_batch: 1
  n_workers: 4
  prefetch: 2
  pin_memory: False

prompt:
  template_dir: assets/prompt_templates
  prompt_type: scoring
  use_example: True
  input_types:
    geometry: ['rgb', 'normal_map']
    texture: ['rgb', 'albedo']
    material: ['rgb', 'metallic_map', 'roughness_map']
    plausibility: ['rgb']
    artifacts: ['rgb']
    preference: ['rgb']

stat:
  src_path: datasets/splits_test/
  out_dir: outputs/stat/