model:
  model_name: Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4
  use_openai_api: False
  api_key:
  temperature: 1.0
  max_tokens: 4096
  n_choices: 3

experiment:
  out_dir: outputs/
  batch_inference: True

data:
  src_path: assets/gobajverse_280k
  example:
    use_example: True
    num_level: 5 
    num_example_sampling: 3
    sample_interval: 20
    sample_offset: 0
    meta_path: assets/example_scores.json
  n_batch: 2
  n_workers: 4
  prefetch: 2
  pin_memory: False

prompt:
  template_dir: assets/prompt_templates
  prompt_type: scoring
  input_types:
    geometry: ['rgb', 'normal map']
    texture: ['rgb', 'albedo']
    material: ['rgb', 'metallic map', 'roughness map']
    plausibility: ['rgb']
    artifacts: ['rgb']
    preference: ['rgb']

stat:
  src_path: assets/splits/
  out_dir: outputs/stat